name: Run Unit Tests

on:
  push:
    branches: [task-3]
  pull_request:
    branches: [task-3]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # Ensure pytest is installed

    - name: Run pytest tests
      run: pytest tests/
      shell: /usr/bin/bash -e {0}
      env:
        pythonLocation: ${{ steps.setup-python.outputs.python-location }}
        PKG_CONFIG_PATH: ${{ env.pythonLocation }}/lib/pkgconfig
        Python_ROOT_DIR: ${{ env.pythonLocation }}
        Python2_ROOT_DIR: ${{ env.pythonLocation }}
        Python3_ROOT_DIR: ${{ env.pythonLocation }}
        LD_LIBRARY_PATH: ${{ env.pythonLocation }}/lib
